### ISSUE TITLE
Search bar looks odd, can't click top two emails, and settings menu is invisible

### ISSUE THREAD

**Issue by Saturable** [jakubzet/mailspring-matcha-theme#1]
I'm not sure if this is intended, but the top bar is all white for me. When I'm in an email thread, the back to inbox button is invisible as well, but can still be clicked.

Here's what it looks like:
![image](https://user-images.githubusercontent.com/27968633/38388009-85a7b66a-38df-11e8-95d6-4914c47c41a8.png)

Futhermore, it seems something is blocking the top two emails in my inbox. I can't click them, but I can click all of the ones below. Also, when I scroll down, the top two visible emails also can't be clicked.

Lastly, the settings hamburger menu is gone. This makes it hard to get to my preferences and such!

**Comment by jakubzet** [comment]
Hi! Can you provide your OS details? So far I tested the theme only on Manjaro Linux with Gnome and Matcha GTK theme.

**Comment by Saturable** [comment]
I'm running Windows 10 Home version 1709. I know other skins for Mailspring don't play very well with Windows either.
