### ISSUE TITLE
Listing on Mailspring Community?

### ISSUE THREAD

**Issue by CodeMouse92** [jakubzet/mailspring-matcha-theme#4]
Mailspring just launched an official Discourse community which will house the catalog for themes and plugins, among other things. It would be great to have this theme listed there: https://community.getmailspring.com/c/themes/9

@jakubzet if you join, we can also add you to the Theme Designers group.

**Comment by jakubzet** [comment]
That's awesome initiative, I'm glad for the invitation! :+1: The theme page could be find here: https://community.getmailspring.com/t/matcha-theme-for-mailspring
