### ISSUE TITLE
Toolbar color bug on Mailspring 1.9.2 Windows

### ISSUE THREAD

**Issue by Rayjjn** [jakubzet/mailspring-matcha-theme#5]
Hello ! I'm loving your theme but i'd like to report an issue. 
I installed the theme on Mailspring 1.9.2 on Windows and the toolbar (i believe it's the name on this element) is white instead of dark.
I ran a bit into the sources and i think that Mailspring on Windows might not have the same ui variables as Linux.
Here is a screenshot :
![bug_matcha](https://user-images.githubusercontent.com/93737978/140413376-ffe77b6f-c65e-4743-bddb-dae6bbe83682.png)
 
Thanks for the good work !
Regards

**Comment by jakubzet** [comment]
Hi Rayjin, and thank you for reporting the issue! I'll do my best to check the reason of this on Windows - however, currently I don't have an access to any Windows machine, as I mainly work on Linux Manjaro.

Nonetheless, I'm keeping the issue open, so as soon as I have an opportunity to use Windows, I'll check things out.

**Comment by wituwitu** [comment]
I also have this problem on Windows. Is there any update? I also noticed that in the theme selection screen, the modal-close.png button is not found, this may give more hints on what's happening. I really like the style of this theme but can't use it :( !

![imagen](https://user-images.githubusercontent.com/43627615/147763695-2d4c4d71-17bf-4a30-bf5f-616615507d56.png)

I think this issue also overlaps with [this one](https://github.com/jakubzet/mailspring-matcha-theme/issues/6#issue-1081473423), I have the same problem as well.

**Comment by jakubzet** [comment]
@wituwitu - unfortunately, I don't have an access to Windows PC, as I use Linux Manjaro on a daily basis.
As soon as I'll have time I'll try to install a virtual machine of some kind and test the theme there.

**Comment by Safibulae** [comment]
> @wituwitu - unfortunately, I don't have an access to Windows PC, as I use Linux Manjaro on a daily basis.
> As soon as I'll have time I'll try to install a virtual machine of some kind and test the theme there.

Were you able to look into this Windows bug? Many thanks in advance!

**Comment by Vaniom** [comment]
Hello @jakubzet , 
Nice theme, I love it!
I also noticed a bug color on the `.sheet-toolbar-container`
I fixed it by adding the following rule to `index.less` (yes, I am to lazy to find the correct component file :p)

```
body.platform-win32 .sheet-toolbar-container,
body.platform-win32.is-blurred .sheet-toolbar-container {
      background-color: @base_color_dark;
}

**Comment by Safibulae** [comment]
> Hello @jakubzet , Nice theme, I love it! I also noticed a bug color on the `.sheet-toolbar-container` I fixed it by adding the following rule to `index.less` (yes, I am to lazy to find the correct component file :p)
> 
> ```
> body.platform-win32 .sheet-toolbar-container,
> body.platform-win32.is-blurred .sheet-toolbar-container {
>       background-color: @base_color_dark;
> }
> ```

You, Sir, are the MVP. THANK YOU!!
