### ISSUE TITLE
The mouse fails to select the first message.

### ISSUE THREAD

**Issue by maverick40** [jakubzet/mailspring-matcha-theme#6]
Hello, I love the theme, but I have a problem. I cannot select the first message. With other theme and official theme no problem. That poses a problem. Could you tell me where I can find the element that changes the selection point with the mouse to successfully select the first post. ?

**Comment by jakubzet** [comment]
Hi @maverick40 - I've just added a new update of theme to master branch. Can you download and check if this solves the issue?
